version: "3.7"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./hcorem.conf:/etc/nginx/conf.d/default.conf"
      - "./html/:/var/www/hcorem/"

  php:
    build:
      context: .
      dockerfile: dockerfile-php
    volumes:
      - "./html/:/var/www/hcorem/"
