version: '3'
services:
  db:
    build: ./
    restart: always
    entrypoint:
      - /docker-entrypoint.sh 
      - -c 
      - 'config_file=/etc/postgresql/postgresql.conf'
    environment:
      POSTGRES_PASSWORD: wonderkun 

  adminer:
    image: adminer
    restart: always
    ports:
      - 7777:8080

      # /var/lib/postgresql/data